version: '2.1'

services:
  master:
    build: ./master
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./docker-host/id_key:/var/key
    environment:
      JENKINS_OPTS: "--prefix=/my-site"
    ports:
       - "8080:8080"
       - "50000:50000"
    links:
      - docker-host
  docker-host:
    build: ./docker-host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home:
